steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      - 'run', 'deploy',
      - ${_SERVICE_NAME},
      - '--image=gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA',
      - '--region=$DEPLOY_REGION',
      - '--platform=$PLATFORM',
      - '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA'

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_PROJECT_ID: portfolioaf
  _PLATFORM: managed
  _SERVICE_NAME: portfolio
  REPO_NAME: portfolio
  _DEPLOY_REGION: asia-southeast2
  _AR_HOSTNAME: asia-southeast2-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy

tags:
  - gcp-cloud-build-deploy-cloud-run
  - portfolio